config/routes.rb
Rails.application.routes.draw do
  get 'braintree/new'
  post 'braintree/checkout'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"

  resources :users, except: [:destroy]
  resource :sessions, only: [:create, :new, :destroy]

  resources :photos, except: [:destroy] do
    resources :likes
    resources :comments
  end

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user

  def self.create_with_omniauth(auth_hash)
    self.new(
      provider: auth_hash["provider"],
      uid: auth_hash["uid"],
      token: auth_hash["credentials"]["token"]
    )
  end

  def update_token(auth_hash)
    self.token = auth_hash["credentials"]["token"]
    self.save
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :users
  belongs_to :photos
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :photo

  validates :user_id, uniqueness: { scope: :photo_id }

end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :photo_url, ImageUploader

  belongs_to :user

  has_many :likes
  has_many :comments

  def like(user)
    likes << Like.create(user: user)
  end

  def unlike(user)
    likes.where(user_id: user.id).first.destroy
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :authentications, dependent: :destroy
  has_secure_password

  validates :username, presence: true
  validates :email, presence: true, uniqueness: true

  has_many :photos, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  def self.create_with_auth_and_hash(authentication, auth_hash)
    user = self.create!(
      username: auth_hash["extra"]["raw_info"]["first_name"],
      email: auth_hash["extra"]["raw_info"]["email"],
      password: SecureRandom.hex(10)
    )
    user.authentications << authentication
    return user
  end

  # grab fb_token to access Facebook for user data
  def fb_token
    x = self.authentications.find_by(provider: 'facebook')
    return x.token unless x.nil?
  end

  #Search Users
  def self.search(search)
    where("username ILIKE ?", "%#{search}%")
  end

  def initials
    self.username.scan(/(\b[a-zA-Z])[a-zA-Z]* ?/).join
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def authenticate!
    unless current_user
      redirect_to root_path
      flash[:danger] = "You need to login first"
    end
  end

  def current_user
    return unless cookies.signed[:id]
    @current_user ||= User.find_by(id: cookies.signed[:id])
  end

  helper_method :current_user

  def logged_in
    @current_user.present? == true
  end

  helper_method :logged_in

end

app/controllers/braintree_controller.rb
class BraintreeController < ApplicationController
  def new
    @client_token = Braintree::ClientToken.generate
  end

  def checkout
    nonce_from_the_client = params[:checkout_form][:payment_method_nonce]

    result = Braintree::Transaction.sale(
     :amount => "10.00", #this is currently hardcoded
     :payment_method_nonce => nonce_from_the_client,
     :options => {
        :submit_for_settlement => true
      }
     )

    if result.success?
      current_user.update_attribute(:boost, true)
      redirect_to :root, :flash => { :success => "Transaction successful!" }
    else
      redirect_to :root, :flash => { :error => "Transaction failed. Please try again." }
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
  end

  def delete
  end  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @user = current_user
    @photo = Photo.find_by(id: params[:photo_id])
    @photo.like(@user)
    flash.now[:success] = "Photo liked"
    respond_to do |f|
      f.js
      f.html { redirect_to photo_path(@photo) }
    end
  end

  def destroy
    @user = current_user
    @photo = Photo.find_by(id: params[:photo_id])
    @photo.unlike(@user)
    flash.now[:danger] = "Photo unliked"
    respond_to do |f|
      f.js
      f.html { redirect_to photo_path(@photo) }
    end
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate!

  def all
    @photo = Photo.find_by(id: params[:id])
    @user = User.find_by(:id)
  end

  def show
    @photo = Photo.find_by(id: params[:id])
  end

  def create
    @photo = current_user.photos.create(photo_params)

    if @photo.persisted?
      redirect_to photo_path(@photo)
      flash[:success] = "New photo posted"
    else
      render :new
      flash[:danger] = "Error posting photo"
    end

  end

  def update
  end

  def delete
  end

  private

  def photo_params
    params.require(:photo).permit(:user_id, :photo_url, :caption, :created_at, :updated_at)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :authenticate!, only: [:destroy]

  include UsersHelper

  def new
  end

  def create
    user = User.find_by(email: user_params[:email])
               &.authenticate(user_params[:password])

    if user
      cookies.permanent.signed[:id] = user.id
      flash[:success] = "Welcome back #{current_user.username}"
      redirect_to photos_path
    else
      flash[:danger] = "Error logging in"
      redirect_to new_sessions_path
    end

  end

  def destroy
    cookies.delete(:id)
    flash[:success] = "You've been logged out"
    redirect_to root_path
  end

  def create_from_omniauth
    auth_hash = request.env["omniauth.auth"]
    authentication = Authentication.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"]) ||  Authentication.create_with_omniauth(auth_hash)

    # if: previously already logged in with OAuth
    if authentication.user
      user = authentication.user
      authentication.update_token(auth_hash)
      @next = root_url
      @notice = "Signed in!"
    # else: user logs in with OAuth for the first time
    else
      user = User.create_with_auth_and_hash(authentication, auth_hash)
      # you are expected to have a path that leads to a page for editing user details
      @next = edit_user_path(user)
      @notice = "User created. Please confirm or edit details"
    end

    sign_in(user)
    redirect_to photos_path

  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.create(user_params)

    if @user.persisted?
      cookies.permanent.signed[:id] = @user.id
      flash[:success] = "You've registered"
      redirect_to root_path
    else
      flash[:danger] = @user.errors.full_messages
      redirect_to new_user_path
    end
  end

  def show
    @user = User.find(params[:id])

    @photos = @user.photos.all

  end

  def index

    if params[:search]
      @users = User.search(params[:search]).order("created_at DESC")
    else
      #  @users = User.all.order('created_at DESC')
     end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :username)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
        when :notice then "alert alert-info"
        when :success then "alert alert-success"
        when :error then "alert alert-error"
        when :alert then "alert alert-error"
    end
  end
end

app/helpers/braintree_helper.rb
module BraintreeHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def sign_in(user)
    cookies.signed[:id] = user.id
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/braintree/new.html.erb
<!-- Load the Client component. -->
<script src="https://js.braintreegateway.com/web/3.6.3/js/client.min.js"></script>
<!-- Load the Hosted Fields component. -->
<script src="https://js.braintreegateway.com/web/3.6.3/js/hosted-fields.min.js"></script>

<h1>Make Payment</h1>

<div class="demo-frame">
  <%= form_for :checkout_form, url: braintree_checkout_path, html: { id: "cardForm"} do |form| %>

    <%= form.label :card_number, "Credit Card Number", html: {class: "hosted-fields--label"} %>
    <div id="card-number" class="hosted-field"></div>

    <%= form.label :expiration_date, "Expiration Date", html: {class: "hosted-fields--label"} %>
    <div id="expiration-date" class="hosted-field"></div>

    <%= form.label :cvv, "CVV", html: {class: "hosted-fields--label"} %>
    <div id="cvv" class="hosted-field"></div>

    <%= form.hidden_field "payment_method_nonce" %>

    <div class="button-container">
      <%= form.submit "Purchase", disabled: true, class: "btn btn-primary", id: "submit-payment-btn" %>
    </div>
  <% end %>
</div>

<script>
  var form = document.querySelector('#cardForm');
  var submit = document.querySelector("#submit-payment-btn");
  var authorization = '<%= @client_token %>';

  braintree.client.create({
    // Replace this with your own authorization.
    authorization: authorization
  }, function (clientErr, clientInstance) {
    if (clientErr) {
      // Handle error in client creation
      return;
    }

    braintree.hostedFields.create({
      client: clientInstance,
      styles: {
        'input': {
          'font-size': '14pt'
        },
        'input.invalid': {
          'color': 'red'
        },
        'input.valid': {
          'color': 'green'
        }
      },
      fields: {
        number: {
          selector: '#card-number',
          placeholder: '4111 1111 1111 1111'
        },
        cvv: {
          selector: '#cvv',
          placeholder: '123'
        },
        expirationDate: {
          selector: '#expiration-date',
          placeholder: '10/2019'
        }
      }
    }, function (hostedFieldsErr, hostedFieldsInstance) {
      if (hostedFieldsErr) {
        // Handle error in Hosted Fields creation
        return;
      }

      submit.removeAttribute('disabled');

      form.addEventListener('submit', function (event) {
        event.preventDefault();

        hostedFieldsInstance.tokenize(function (tokenizeErr, payload) {
          if (tokenizeErr) {
            // Handle error in Hosted Fields tokenization
            return;
          }

          // Put `payload.nonce` into the `payment_method_nonce` input, and then
          // submit the form. Alternatively, you could send the nonce to your server
          // with AJAX.
          document.querySelector('input[name="checkout_form[payment_method_nonce]"]').value = payload.nonce;
          form.submit();
        });
      }, false);
    });
  });

</script>

app/views/likes/_counter.html.erb
<p><%= photo.likes.count%> likes</p>

app/views/likes/_create.html.erb
<!-- Liking a photo -->
<%= link_to "Like", photo_likes_path(@photo), method: :post, remote: true %>
<%= link_to "Unlike", photo_like_path(@photo), method: :delete, remote: true %>
<!-- Liking a photo -->

app/views/likes/create.js.erb
document.getElementById('flash-messages-container').innerHTML = "<%=j render partial: 'layouts/flash_messages' %>"
document.getElementById('likes-counter-container').innerHTML = "<%=j render partial: 'likes/counter', locals: { photo: @photo } %>"

app/views/likes/destroy.js.erb
document.getElementById('flash-messages-container').innerHTML = "<%=j render partial: 'layouts/flash_messages' %>"
document.getElementById('likes-counter-container').innerHTML = "<%=j render partial: 'likes/counter', locals: { photo: @photo } %>"

app/views/photos/index.html.erb
<h2 class="header-title">Browse Instasnap</h2>

<div class="photos-index">
  <% Photo.all.each do |photo| %>
    <%= image_tag photo.photo_url, class: 'index-photo' %>
    <div class="photo-text">
      <p><%= photo.likes.count%> likes</p>
      <%= link_to "#{photo.caption}", photo_path(photo.id), class: 'caption' %>
      <p>Posted by: <%= link_to "#{photo.user.username}", user_path(photo.user.id) %></p>
    </div>
    <hr>
  <% end %>
</div>

app/views/photos/new.html.erb
<section class="photos new">
  <div class="content">
    <div class="new-photo">
      <%= form_for(:photo, :html => {:multipart => true} ,url: photos_path, method: :post) do |f| %>
        <h1 class="text-center">Post new photo</h1>
        <br>
        <div class="form-group">
          <%= f.hidden_field :user_id, value: current_user.id %>
        </div>

        <div class="form-group">
          <h4><%= f.label :photo_url, "Picture", class: ''%></h4>
          <%= f.file_field :photo_url, id: "post_photo_field", class: "form-control" %>
        </div>

        <div class="form-group">
          <h4><%= f.label :caption, "Caption", class: '' %></h4>
          <%= f.text_field :caption, id: "photo_caption_field", class: 'form-control' %>
        </div>

        <div class="form-group text-center">
          <%= f.submit "Post new photo", class: 'btn btn-primary btn-lg' %>
        </div>
      <% end %>
    </div>

    <h5 class= "text-center">
      <%= link_to "Return to home", root_path, class: '' %>
    </h5>
  </div>
</section>

app/views/photos/show.html.erb
<html>
  <body>
    <section class="photo">
      <div class="show-photo">
        <div class="image-container">
          <%= image_tag @photo.photo_url %>
        </div>

        <div class="caption-container">
          <%= render partial: 'likes/create' %>
          <div id="likes-counter-container">
            <%= render partial: 'likes/counter', locals: { photo: @photo } %>
          </div>
          <h4><%= @photo.caption %></h4>
        </div>


        <div class="back">
          <%= link_to "Back", photos_path %>
        </div>

      </div>
    </section>
  </body>
</html>

app/views/users/_user.html.erb
<h3>Search results</h3>

<%= link_to "#{@users.find_by(id: @users).username}", user_path(@users.find_by(id: @users)) %>

app/views/users/edit.html.erb
<h3>Edit profile</h3>

app/views/users/index.html.erb
<div class="search-page">

  <div class="search-users">
    <%= form_tag(users_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search Users" %>
      <%= submit_tag "Search", class: 'btn btn-info search-btn' %>
    <% end %>

    <% if @users.present? %>
      <%= render partial: 'user' %>
    <% else %>
      <p>There are no users matching the term(s) <%= params[:search] %>.</p>
    <% end %>
  </div>


</div>

app/views/users/new.html.erb
<section class="users new">
  <div class="content">
    <div class="new-signup-form">
      <%= form_for(:user, url: users_path, method: :post) do |f| %>
        <h1 class="text-center">Sign Up</h1>
        <br>
        <div class="form-group">
          <h4><%= f.label :email_field, "Email", class: '' %></h4>
          <%= f.email_field :email, required: true, id: "user_email_field", class: "form-control" %>
        </div>

        <div class="form-group">
          <h4><%= f.label :username, "Username", class: '' %></h4>
          <%= f.text_field :username, required: true, id: "user_username_field", class: 'form-control' %>
        </div>

        <div class="form-group">
          <h4><%= f.label :password_field, "Password", class: '' %></h4>
          <%= f.password_field :password, required: true, id: "user_password_field", class: 'form-control'%>
        </div>

        <div class="form-group text-center">
          <%= f.submit "Sign me up!", class: 'btn btn-primary' %>
        </div>
    </div>

    <% end %>

    <h5 class="text-center">
      <%= link_to image_tag('https://i.stack.imgur.com/Vk9SO.png'), "/auth/facebook" %>
      <br><br>
      <%= link_to "Return home", root_path, class: '' %>
    </h5>
  </div>
</section>

app/views/users/show.html.erb
<h3 class="profile-title">
  <%= @user.username%>'s Profile

  <% if @user.boost != true %>
    <i class="fa fa-user-circle" aria-hidden="true"></i>
  <% else %>
    <i class="fa fa-user-circle" aria-hidden="true"></i>
    <i class="fa fa-star" aria-hidden="true"></i>
  <% end %>

</h3>

<div class="user-photos">

  <% @photos.each do |photo| %>
    <%= image_tag photo.photo_url %>
    <br>
    <div class="caption">
      <%= link_to "#{photo.caption}", photo_path(photo.id), class: 'caption' %>
    </div>
    <br>
    <br>
  <% end %>


</div>

app/views/welcome/index.html.erb
<div class="main-page">
  <div class="header">
    <h1>Welcome to Instasnap</h1>
  </div>

  <div class="main-content">

    <% if current_user%>
    <div class="all-photos">
      <p>Browse all photos</p>
      <%= link_to "All Photos", photos_path %>
    </div>

    <div class="buy-boost">
      <i class="fa fa-star" aria-hidden="true"></i>
      <%= link_to "Buy Boost", braintree_new_path %>
      <i class="fa fa-star" aria-hidden="true"></i>
      <p>If you're looking to boost your profile, you can buy lifetime access for only $10!</p>
    </div>

    <% else %>
    <div class="signup-form">
      <h4><%= link_to "Sign up for an account today!", new_user_path %></h4>
      <p>OR</p>
      <h4><%= link_to "Login to your account", new_sessions_path, class: '' %></h4>
      <br>
<!--       <div class="fb-login">
        <%= link_to image_tag('https://i.stack.imgur.com/Vk9SO.png'), "/auth/facebook" %>
      </div> -->
    </div>

    <% end %>

  </div>
</div>